services:
  node:
    image: node:latest
    container_name: node
    user: "${UID}:${GID}"
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"